set(DATALOCATION "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATADIR}/BGStudio/BGCMS" CACHE STRING "")
set(CMSRPATH "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}:${BGMRPC_CLIENT}/${CMAKE_INSTALL_LIBDIR}" CACHE STRING "")
