#ifndef SNIPPETPLUGIN_GLOBAL_H
#define SNIPPETPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SNIPPETPLUGIN_LIBRARY)
#  define SNIPPETPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define SNIPPETPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SNIPPETPLUGIN_GLOBAL_H
